#!/bin/bash -ex

yum install -y epel-release
yum install -y python-pip
pip install --upgrade ansible
ansible-galaxy install vincentclee.test_tools --force
ansible-playbook ~/.ansible/roles/vincentclee.test_tools/playbook.yml
